[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo =  'othree/yajs.vim'
on_ft = ['js', 'jsx']

[[plugins]]
repo =  'maxmellon/vim-jsx-pretty'
on_ft = ['js', 'jsx']

[[plugins]]
repo =  'othree/javascript-libraries-syntax.vim'
on_ft = ['js', 'jsx']

[[plugins]]
repo =  'othree/es.next.syntax.vim'
on_ft = ['js', 'jsx']