[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = "Shougo/neosnippet"

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'tacahiroy/ctrlp-funky'

[[plugins]]
repo = 'suy/vim-ctrlp-commandline'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'wakatime/vim-wakatime'
